name: Build Docker images

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id_token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend_api image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./frontend_api/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/frontend_api:latest

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.repository }}/frontend_api
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Build and push device_api image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./device_api/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/device_api:latest
          
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.repository }}/device_api
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true